// config.js
const fs = require("fs");
require("dotenv").config();

const config = {
  SESSION_ID: process.env.SESSION_ID || "eyJub2lzZUtleSI6eyJwcml2YXRlIjp7InR5cGUiOiJCdWZmZXIiLCJkYXRhIjoic0tJZytVajJzN1NsbDF3cXIyRzV3RmtDa0FMM0lWdkdQSlVTVEphSXlGND0ifSwicHVibGljIjp7InR5cGUiOiJCdWZmZXIiLCJkYXRhIjoiS2hGYVlXcFhOZGEzdU1CTWhpSXRqWWV5TlcrVjNwQlBFTUF2VkJ4Nk9RND0ifX0sInBhaXJpbmdFcGhlbWVyYWxLZXlQYWlyIjp7InByaXZhdGUiOnsidHlwZSI6IkJ1ZmZlciIsImRhdGEiOiJtTm5YUzdwVXJYOUJKNnh5M2paTW1PK1RtVUc3ZERCOTBFU29xT0liTW1RPSJ9LCJwdWJsaWMiOnsidHlwZSI6IkJ1ZmZlciIsImRhdGEiOiI5d3hVa1VSdldLeDFUNFRWSituSzNMYStmSUN3QUtCTnNHaXRvYWlmU2d3PSJ9fSwic2lnbmVkSWRlbnRpdHlLZXkiOnsicHJpdmF0ZSI6eyJ0eXBlIjoiQnVmZmVyIiwiZGF0YSI6ImtEM0J6SHJDMThJNWZwN3lmNGFYYWc0TG14QVFKMlJCbW1NUDJjUEM4Vm89In0sInB1YmxpYyI6eyJ0eXBlIjoiQnVmZmVyIiwiZGF0YSI6Ik1HT3ZkS0hRWnNQNVdPcm04eEtXTW1ja3JVRHA3ZmtiZXpGQXBaZUZ4bEU9In19LCJzaWduZWRQcmVLZXkiOnsia2V5UGFpciI6eyJwcml2YXRlIjp7InR5cGUiOiJCdWZmZXIiLCJkYXRhIjoiUVB3Q29ZZUpGU0NjM0YxNVh5dkp2MzRYMmEwemxneWJxZlZzWmNkbmZWcz0ifSwicHVibGljIjp7InR5cGUiOiJCdWZmZXIiLCJkYXRhIjoiZGhLVEd5V3Q1Uy9jRFFjejhBT0JLOVR0RjBiUWxQRGtHcWVMM1R0ZUptbz0ifX0sInNpZ25hdHVyZSI6eyJ0eXBlIjoiQnVmZmVyIiwiZGF0YSI6Ik9PRVlETWxFYU9US0xHdHlUb25jTHkrY3BZWC9TZ3IxcTNlWGtSbXRnSGxzREJBS3pUeW00WnVVME1YMEV6Yy9KVi9tSFcrdEFHV2lIR1kzTjZORUJnPT0ifSwia2V5SWQiOjF9LCJyZWdpc3RyYXRpb25JZCI6NTUsImFkdlNlY3JldEtleSI6Ik9JSHBIUlpDNWlWSmEzQW1sakkvZEVNMy9XZ3pvaTJqRURqTjh6Snd3Tm89IiwicHJvY2Vzc2VkSGlzdG9yeU1lc3NhZ2VzIjpbeyJrZXkiOnsicmVtb3RlSmlkIjoiMjU0NzQ3MTY2NTUxQHMud2hhdHNhcHAubmV0IiwiZnJvbU1lIjp0cnVlLCJpZCI6IkFGMTlDMDY0RkUyRTVDMDc2MDI4QkNGRjcyREE2OTY4In0sIm1lc3NhZ2VUaW1lc3RhbXAiOjE3MjgzOTA2ODh9XSwibmV4dFByZUtleUlkIjo2MSwiZmlyc3RVbnVwbG9hZGVkUHJlS2V5SWQiOjYxLCJhY2NvdW50U3luY0NvdW50ZXIiOjAsImFjY291bnRTZXR0aW5ncyI6eyJ1bmFyY2hpdmVDaGF0cyI6ZmFsc2V9LCJkZXZpY2VJZCI6IlJDNnJiU2g0UmxxNkdMRFVydmpPYVEiLCJwaG9uZUlkIjoiZjQ0NDU3N2YtOTYxMS00YzJlLWI5ZDQtNzUyOTIwMTdmYTNlIiwiaWRlbnRpdHlJZCI6eyJ0eXBlIjoiQnVmZmVyIiwiZGF0YSI6IkFUVHVMMWVRSVdneG9PckYzeDlxRVZGVU9Scz0ifSwicmVnaXN0ZXJlZCI6dHJ1ZSwiYmFja3VwVG9rZW4iOnsidHlwZSI6IkJ1ZmZlciIsImRhdGEiOiJoaG1abmJ1NVptdjhldkRkd1RLVTZBOTZmeXc9In0sInJlZ2lzdHJhdGlvbiI6e30sInBhaXJpbmdDb2RlIjoiTlNLWkY5WTEiLCJtZSI6eyJpZCI6IjI1NDc0NzE2NjU1MToxNkBzLndoYXRzYXBwLm5ldCIsIm5hbWUiOiJUayJ9LCJhY2NvdW50Ijp7ImRldGFpbHMiOiJDTGpYZ29VREVJN01sTGdHR0FvZ0FDZ0EiLCJhY2NvdW50U2lnbmF0dXJlS2V5IjoicFd4VG4wd3hhTy8rQ25IQmpEQVUyam54RUwzTUY1MStzRjNTbXc3RlFGVT0iLCJhY2NvdW50U2lnbmF0dXJlIjoiRDRVZGN0U0NhTSt1clIzNERCemcrYWtzU29ldFNrY3RlN25CTmMxdGRZMzRPcHR0VE5aSG13UDlIR0RmTGU4M29zdUFKSDFveWhPeWxSc2RXZEhtQUE9PSIsImRldmljZVNpZ25hdHVyZSI6ImFzR1dvVy8zeHJqZHExN1lHdHNOMmYzMnNVK0ZqMW1XM3ZtOE9zbFpSd2lsNG9mbTBxR0pxcFlNamp4MDNLdlFRQm5hU1o3bDBVSmw3SW0xRFQrZkJnPT0ifSwic2lnbmFsSWRlbnRpdGllcyI6W3siaWRlbnRpZmllciI6eyJuYW1lIjoiMjU0NzQ3MTY2NTUxOjE2QHMud2hhdHNhcHAubmV0IiwiZGV2aWNlSWQiOjB9LCJpZGVudGlmaWVyS2V5Ijp7InR5cGUiOiJCdWZmZXIiLCJkYXRhIjoiQmFWc1U1OU1NV2p2L2dweHdZd3dGTm81OFJDOXpCZWRmckJkMHBzT3hVQlYifX1dLCJwbGF0Zm9ybSI6InNtYmEiLCJsYXN0QWNjb3VudFN5bmNUaW1lc3RhbXAiOjE3MjgzOTA2ODMsIm15QXBwU3RhdGVLZXlJZCI6IkFBQUFBRzBuIn0=",
  PREFIX: process.env.PREFIX || '.',
  AUTO_STATUS_SEEN: process.env.AUTO_STATUS_SEEN !== undefined ? process.env.AUTO_STATUS_SEEN === 'true' : true, 
  AUTO_DL: process.env.AUTO_DL !== undefined ? process.env.AUTO_DL === 'true' : false,
  AUTO_READ: process.env.AUTO_READ !== undefined ? process.env.AUTO_READ === 'true' : false,
  AUTO_TYPING: process.env.AUTO_TYPING !== undefined ? process.env.AUTO_TYPING === 'true' : false,
  AUTO_RECORDING: process.env.AUTO_RECORDING !== undefined ? process.env.AUTO_RECORDING === 'true' : false,
  ALWAYS_ONLINE: process.env.ALWAYS_ONLINE !== undefined ? process.env.ALWAYS_ONLINE === 'true' : false,
  AUTO_REACT: process.env.AUTO_REACT !== undefined ? process.env.AUTO_REACT === 'true' : false,
   /*auto block only for 212 */
  AUTO_BLOCK: process.env.AUTO_BLOCK !== undefined ? process.env.AUTO_BLOCK === 'true' : true,
  
  
  REJECT_CALL: process.env.REJECT_CALL !== undefined ? process.env.REJECT_CALL === 'true' : false, 
  NOT_ALLOW: process.env.NOT_ALLOW !== undefined ? process.env.NOT_ALLOW === 'true' : true,
  MODE: process.env.MODE || "public",
  OWNER_NAME: process.env.OWNER_NAME || "©Baraka Bega",
  OWNER_NUMBER: process.env.OWNER_NUMBER || "255762190568",
  GEMINI_KEY: process.env.GEMINI_KEY || "AIzaSyCUPaxfIdZawsKZKqCqJcC-GWiQPCXKTDc",
  WELCOME: process.env.WELCOME !== undefined ? process.env.WELCOME === 'true' : false, 
};


module.exports = config;
